### ISSUE TITLE
Missing imageminJpegRecompress as dependency

### ISSUE THREAD

**Issue by soleo** [GoogleChrome/essential-image-optimization#58]
Cannot build default gulp task because of missing imageJpegRecompress

```gulp
[21:17:34] Requiring external module babel-register
[21:17:36] Using gulpfile ~/projects/essential-image-optimization/gulpfile.babel.js
[21:17:36] Starting 'clean'...
[21:17:36] Finished 'clean' after 45 ms
[21:17:36] Starting 'default'...
[21:17:36] Starting 'markdown'...
[21:17:36] Finished 'markdown' after 20 ms
[21:17:36] Starting 'lint'...
[21:17:36] Starting 'html'...
[21:17:36] Starting 'scripts'...
[21:17:36] Starting 'images'...
[21:17:36] Starting 'copy'...
[21:17:36] html index.html 188.49 kB
[21:17:37] Finished 'lint' after 580 ms
[21:17:37] scripts all files 7.28 kB
Unhandled rejection Error: spawn ~/projects/essential-image-optimization/node_modules/jpeg-recompress-bin/vendor/jpeg-recompress ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[21:17:37] Finished 'scripts' after 926 ms
[21:17:37] copy all files 46.81 kB
[21:17:37] Finished 'copy' after 851 ms
[21:17:44] Finished 'html' after 7.47 s```

**Comment by soleo** [comment]
never mind, It was an incomplete `npm install`
